### ISSUE TITLE
build failed as stdatomic.h is missing

### ISSUE THREAD

**Issue by Zhaojp-Frank** [yalue/cuda_scheduling_examiner_mirror#3]
thanks for sharing at first, 
I am trying to build from scratch but hit a header file missing problem? could u double check stdatomic.h is there? thanks a lot

gcc -c -Wall -Werror -O3 -g -fPIC -o obj/task_host.o src/task_host.c
In file included from src/task_host.c:20:0:
src/barrier_wait.h:6:23: fatal error: stdatomic.h: No such file or directory

**Comment by Zhaojp-Frank** [comment]
closed as the header file is from GCC, and it's missing in gcc4.8 due to GNU bug, now the issue was fixed after upgrade GCC i.e., to 6.4.

**Comment by yalue** [comment]
Thanks for the comment, and sorry I didn't happen to log in to github before you fixed it!  I'm glad you ended up working it out.
